packages:
  # 匹配packages下所有一级子目录
  - 'packages/*'
  - 'apps/*'
allowBuilds:
  core-js: true
  core-js-pure: true
  esbuild: true
catalog:
  '@vue/tsconfig': ^0.7.0
  typescript: ^5.8.3
  vue-tsc: ^2.2.12
